import QtQuick 2.0

ListModel {
    id:listBtn

    ListElement{
        btnLabel:"%"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }
    ListElement{
        btnLabel:"CE"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }
    ListElement{
        btnLabel:"C"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }
    ListElement{
        btnLabel:"DEL"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }

    ListElement{
        btnLabel:"1/x"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }
    ListElement{
        btnLabel:"x^2"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }
    ListElement{
        btnLabel:"Sqrt(x)"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }
    ListElement{
        btnLabel:"/"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }

    ListElement{
        btnLabel:"7"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"8"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"9"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"x"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }

    ListElement{
        btnLabel:"4"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"5"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"6"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"-"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }

    ListElement{
        btnLabel:"1"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"2"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"3"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"+"
        btnColor:"#323232"
        prsColor:"#3b3b3b"
    }

    ListElement{
        btnLabel:"+/-"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"0"
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"."
        btnColor:"#3b3b3b"
        prsColor:"#323232"
    }
    ListElement{
        btnLabel:"="
        btnColor:"#4cc2ff"
        prsColor:"#3381aa"
    }

}
